Workaround for layer names issue with importance-sampling
ValueError: The name "input_1" is used 2 times in the model. All layer names should be unique.